language: scala
scala:
- 2.11.6
services:
- mongodb
jdk:
- oraclejdk8
after_success:
- sbt dist
env:
  global:
  - secure: HvWsOUcLVPcD9jC2/yLMJnsOb/j+vmAIT0/B12S8GRqG+h31BSFCGvXKQ/+I3zt1cOa2go1/yXuNbiHqC6JKbI2VCn1D+9r28joNYipes345oU9T46Q//uZ5jbwd/4nf91kR5bkQR4ZAyQ8eajIFDpedyd5zLNJYYPQLLA7F8M+ucq1UdNpWv0JhkY/XCCya/NiggiTNwRM5QzoOPIvqzfjhfDgaZDHgrTqItBHRjITcDn1u5ZMjSvpw5PJAkxE0GZi44UqRDOt9IEhonpMA2b+4oKSe+Xvqc523WkEAMyEyIfbGrZ6dHE4Wc4vuWTu3UoqVJ0wNoLkBRDKJPvVKMr0ZhizP4MWd8qsmPCCPQNJA0sYWGV0IRiI7bhwJoqeBplIyCoHhjYPFNZDb/o06Irf5IkSDc00DFRh8ANQQ28HPzXhqfwHgMWHMIEyrvTwjQatDGZedM3HVXS8dMNoHEfslaCwZYMq/GdEH2Z9nWEtpBqp/GoOgHNK0p8Yv8bsJTNoM1QYzoaIFWbHgSi5WoAdrE9hgcfrsP6XoilNfOib7roU6DEH1ULFl23H68jiDrnEPwajuSrmcYx1b+rxRsRewSJ5FsqhgT4TejG+sk4Wec5cAK46Q7y6T0AC6hoA8SMvsgsA2W2JzQVouN/9i8goR9Pm/0lvuT+x2UqFBzxk=
  - secure: JLhpK3/MSAxCZPkG2tgS0OhBwwOD2mZLTHjuw9fK1sunRjDm0LDWdtLak1xJDkj385DmA8ElPtnPpWSfy0FW+V7qTzI/zOgBecalVR93TjDSkafZ9VIvWhgqwQTZip9eLyKPpBcU9isC7dy3JVTN1dNfTAYH59JXVUabp8QyHrgS10CqShZUVukwHiEpAAfhIcEY2qzkhxeOxjDWcBShXHcTuv0c+WsKAVUGGKxe8w+5YGgAYuohivcZQzjwv1zhAT7ry0TdTQZHHYxhDy5F9vEQIBab0tBcVJGgTlRB1PfSjZ2UZ0SPPVDpPYuk95M3nOIDeJ5D6TLWqkxprgAL+ZwhCVTPzMUQfukuj9pWWjceWKovpXmHYD6Y0T8AnZL8IscT0xIR3jE+4yZI+/7NxIn3WaK9TO81ITffUF505pZU+SwjWiSYzgjgRS8+lVlmVaMD9dnoXQrMziA01sYTF830510+2SxDzZuuFBqjKpLXCu89NarE1Cdy1EeLwkTZfzMbpFR35OTbZPbeR9VFLfGwWnPO0bhxxUeqQGSUVaPk4Hip3qKplGAHVt9zzoICLEn4W/lROTMDo2WvOi0lsBFzkD9yv9SKROZOUD4D4AQjjJjv9kC97NUFMZ6gIXDV8/gr5kI9GJWEcxxvNd4kHEJkpjDIE0xAaZuwnqrDhGg=
